### ISSUE TITLE
Auras timer function.

### ISSUE THREAD

**Issue by freesay** [Kkthnx/KkthnxUI_WotLK#64]
![wowscrnshot_062916_110637](https://cloud.githubusercontent.com/assets/19500175/16445077/ac74017e-3de9-11e6-838c-c0fee82f80fb.jpg)

**Comment by Kkthnx** [comment]
I plan to go through today and clean up all left over and old strings and config options left over. I have been going through and starting to piggyback off blizzard options instead of making new ones for the UI.

Я планирую пройти сегодня и убирать все оставшиеся и старые строки и параметры конфигурации осталось. Я шел до конца и начинают контрейлерных от метель варианты вместо создания новых для пользовательского интерфейса.
